### PR TITLE
Enhancement: disable (grey out) sab config form fields whilst sabnzbd is running

### PR DESCRIPTION
**Pull request by overbyrn**
This PR updates sabnzbd.php such that form fields (eg. installdir, datadir, user etc) are all set to disable (greyed out) whilst sabnzbd is running.  Prevents user confusion as to when they are allowed to type into the edit fields. 

Change essentially is made up of three things;
1) all field arguements have been given an "id" tag
2) checkruning javascript function references field arguments by their id and sets disabled when sabnzbd is running
3) validateform javascript function changes disabled state upon form submission.  needed as fields set to disabled do not pass their values upon form submission so we need to change them back to enabled as otherwise rc script will not see them as parameters.

### CODE REVIEW

**Comment by Benni-chan** [comment]
this was already included in my original version of the plugins (in a simpler way)...
i'd like to wait for influencer. maybe there was a good reason, this had been removed...

**Comment by overbyrn** [comment]
Yes, I remember it was "function checkINSTALLDIR(form)" in your original plugin.  I went with this as I needed a validate form function for other plugins I'd developed, so by the time I got around to looking at doing something similar for sab, I took the method I already knew.  Granted there's more than one way to skin a cat.  Too many in fact!  As you say, let's have Influencer have the final say.  I've a fix for HTTPs which I'd like to do a PR for, but will wait as would like to get this sorted first as the https change also includes a potential new form field so has a semi-dependency on this PR.

**Comment by Influencer** [comment]
I had originally kept the feature when I started maintaining these, I removed it so that settings could be changed without having to first stop/disable the plug-in, change settings, and then re-enable. Instead the fields can be changed and take effect immediately by stopping the plug-in, completing the settings change, and then restarting.

Other than the semi-dependency, is there a pressing reason to revert? I get it could cause some confusion, but it seems more intuitive to be able to change the settings without the added steps.

I'm fine with merging if it both of you think it'd be best.

**Comment by Benni-chan** [comment]
i just had a look at the code. since the app it restarted by the plugin everytime the settings are changed, it's not really necessary to disable the inputs.
would it be otherwise (user has to restart the app himself for the new settings to be used), i would vote for these changes. but as it is, i don't really think, there would be much confusion with the settings...

**Comment by Influencer** [comment]
Thats my thoughts, overbyrn, do you agree? And without seeing the other PR your wanting to do, I assume the semi-dependency is in the fact it is disabled as well. Would it be possible to rewrite it as well?

Only reason I'm hesitant is having the plug-in restart the app removes a step, which is a little closer to my goal of these being as simple and easy to use as possible.

**Comment by overbyrn** [comment]
Hi guys, happy to give it a miss if you don't think it'll add value.  I hear what you're saying about keeping things as simple as possible.  For me, I quite like how having fields greyed out helps shout "process running".  I think it's a case of personal preference in the end.

As for the https PR dependency, yes it's mainly that as part of that proposed change I have included an additional contextual form field which shows HTTPS port when one is defined from sabnzbd.ini.  I'm not a huge user of git and rather than stress over keeping branches in sync etc I thought I'd do one at a time.  

I'll go ahead and do a PR for the HTTPS as the code is based on current mainline as of Benni-chan's earlier pull of my fix to checkconfig.

**Comment by Influencer** [comment]
We'll pass for now, I'd suggest leaving the branch open so if we decide to go this route in the future it will simpler to implement.

**Pull request closed without merging**
