### PR TITLE
upgraded python anda few other packages..

### PR DESCRIPTION
**Pull request by sacretagent**
tested them all on my system and working fine

### CODE REVIEW

**Comment by sacretagent** [comment]
forget about it ... have issues after a reboot

**Comment by bbaldino** [comment]
What sort of issues did you see?  Looks like CouchPotato actually requires Python 2.7.3 at this point (says so in the README and I'm seeing some errors with 2.6.6) so would be great to get an updated Python version.

**Comment by Influencer** [comment]
I'm without internet access at home until probably next Friday. I moved and
have been given the run around, 2 weeks and 3 techs later I said screw it
and cancelled my service, new service should be connected next Friday. I'll
visit this then and hopefully get these packages updated.

**Comment by Influencer** [comment]
I pulled these to the Update-Packages branch until I can run through them all. Have you been running the updated versions? If so I can probably just push them to master.

**Pull request closed without merging**
