### PR TITLE
rework https enablement, port & pid checking logic

### PR DESCRIPTION
**Pull request by overbyrn**
Revised how rc.sabnzbd and sabnzbd.php determines when https is enabled and what port to use in that situation. 

This pull request tries to resolve the following issue;

rc.sabnzbd assumes if https is enabled, then there will be a value in https_port.  This is not always the case as it is possible for sabnzbd to have this field blank where it will use HTTPS over the value in regular port ini entry.  The current logic is not sufficient to account for all eventualties.

sabnzbd.php has been amended to include additional logic for how to determine if sabnzbd is running based on whether https is enabled and what port is in use.

An additional form field has been contextually added to show when HTTPS is enabled and https_port contains a value.

There are still some gaps in the logic:

1) php form field "HTTPS Port" will only be displayed in the webgui when https is enabled and https_port  contains a value different than that in port.  For form field exists solely to be informative to the user.  There exists a scenario where https is enabled but https_port field is empty, thus using HTTPS over value stored in regular port.  Using current logic, "HTTPS Port" form field will not display under these circumstances, meaning that webgui will show "HTTP Port" and whilst the value in this field is accurate, SAB is actually using HTTPS over this port.  This could lead to user confusion.  Perhaps it is best to hide the HTTPS port value at all times. Or add an extra contextual change so that "HTTP Port" form field becomes "HTTPS Port" when https is enabled but https_port has no value.

2) Changing HTTPS config from inside SABnzbd webgui can lead to issues in the plugin. The user always has the option to make changes within SABnzbd and hit the built-in restart button.  This can cause the rc.script and php file to get out of sync such as the script may try to stop an existing instance of SAB but against the wrong port and/or php file wrongly detects SAB as running/not running.

However, I think the included changes go some way to ensuring both HTTP and HTTPS ports are managed correctly.

### CODE REVIEW

**Comment by Benni-chan** [comment]
as you've written in the commentary, the https field should be read_only. otherwise the user would think, he could change the https port from that form.

to work around your second issue, i guess we could search for any sabnzbd-*.pid file inside /var/run/sabnzbd without knowing at this time, which ports are used... that way, it wouldn't matter, if the port was changed.
the target when stopping the app should be, that there is no pid file left in /var/run/sabnzbd
(it would be strange, if someone was using two installations of sabnzbd on the same machine, in my opinion. and it would be something, that is not supported by this plugin)

**Comment by overbyrn** [comment]
Will add the readonly if needed.  Wanted to run the whole PR past you guys before tweaking further as there's still a part of me that questions if it's wise to show the HTTPS port in the plugin gui at all.

If multiple instances aren't supported, that'd certainly help a lot and would remove the need for using PIDPORT to keep track of what sab has created as a pid file compared to what is configured for HTTP / HTTPS.  Would remove some of the problems which could come from users making changes in the sab config gui too.

Thinking out loud here... sab is a bit of a pain for writing the pid with https port when https is enabled but the regular port when not.  Perhaps it'd be easier to manually generate the pid, rather than use -pid param.  Might make things a bit easier?

**Comment by Influencer** [comment]
I would agree that multiples are not supported. I cannot see why someone would want to run multiple instances of sab.

We could do as Benni suggests and just look for sabnzbd-*.pid, we actually only use the pid for two things, #1 is verification that sab is running(since as he stated, ideally the pid wouldn't exist if the app has stopped), and #2 as a fallback for stopping sab. First we try to stop sab the way it is designed to be stopped, by sending the command to the webgui to shutdown. If this doesn't work we fall back and kill the pid.

**Comment by overbyrn** [comment]
Ok, when I get time I'll revisit and simplify based on the assumption there's never going to be multiple instances.  

@ Influencer, what're your thoughts regarding showing HTTPS to the user via a webgui form field?  Do you think it's required?  I'm on the fence in so much as I quite like it to show as then I know "hey sab has https enabled and yea that's the port I gave it", verses not showing it at all and assuming if the user is bright enough to enable https in the first place, they'll manage it from Sab's own gui config so don't bother cluttering up the plugin.  The caveat is that it's _possible_ to only have http port defined in sabnzbd.ini but running as https on that port.  So then what is presented to the user via plugin webgui is a bit mixed-up.

I think the logic should be: 
if https is disabled, show http port in webgui
if https is enabled and https port is defined, _either_ show both http and https in webgui or only one of them
if https is enabled and https port is empty, show http port (which https is running over) in the webgui but name it https as it'll be an https url needed to access the sab instance.

Lastly, may also affect what hyperlink is required when showing "Running" in webgui.

**Comment by Influencer** [comment]
I think its a good idea to show the HTTPS port, and your logic works out the way I'd do it as well.

What I'd do is leave the form side how it is, and instead add the information to the "status" side of the screen, perhaps above where it currently shows what the storage memory usage is.

So if https is disabled, show
Running on:
HTTP: 8080

If https is enabled and https port is defined:
Running on:
HTTP: 8080
HTTPS: 9090

If https is enabled and https port is empty:
Running on:
HTTPS: 9090

It seems logical that if the user is accessing unraid GUI they are within the local network and https is not a must, so in the first two cases (where HTTP is running) the "RUNNING" link should point to the HTTP port.

In the final case where HTTPS is the only one running, the link should be modified to point to the HTTPS url.

Going the way you suggested will already have the logic and checks there for this, and I think it will make it much cleaner.

Thanks by the way, I've been meaning to clean up the HTTP/HTTPS logic but haven't found the time to do it lately.

**Comment by overbyrn** [comment]
I promise to revisit this very soon.  Admit to letting it go cold in favour of other things and now I'm procrastinating, knowing that I have to get back up to speed with the code.

**Pull request closed without merging**
