### PR TITLE
HTTPS Fixes for SABnzbd

### PR DESCRIPTION
**Pull request by overbyrn**
Ok gents, this is my second attempt at tidying up https functionality in sabnzbd.  If you get a chance to review this soon I'd appreciate it as it took me _forever_ to get back up to speed with this and I'd like to close this off whilst it's still fresh in my mind.  Accounting for all the permutations of setting up http/https is a royal pain in the neck.  I think I've got it down, but there could be some glitches.  The main thing to bare in mind is that restarting SAB from within its own gui seems to cause the daemon to not restart.  I am assuming officiall support for stopping and starting sab is only from within the unraid plugin.  That would certainly close off a few issues.  Either way, I've tried to account for situations where a user configures https from sab gui and does hit restart.  If the daemon dies, then they will likely go back to unraid sab gui.  Without a refresh they'll still have stop/restart and that should be sufficient to kick the daemon off.  If they previously closed the unraid sab gui page, then reentering it should determine sab is not running and allow to start as normal. 

As stated there are quite a few scenarios where things can go wrong, but on the whole I think I've caught the main ones.

Please give it a look over and let me know your thoughts.

### CODE REVIEW

**Comment by overbyrn** [comment]
I've reworked the stop function.  Separated out the code used to probe what ports sab is running on into it's own function so it's callable by the stop function and also sabnzbd_status() portinfo.  Now the code should try to work out what port(s) are active.  It really only boils down to a couple of permutations.  It simplest to say the URL will only need to use https:// when https is enabled but https_port has no value.  ie. it's using the value from regular http port.  In both other cases (http only / http&https), we can use the regular http port to shut it down.

I've not checked deeply so it might be obvious, but I would love to know the reason why restarting the daemon from within SABnzbd gui seems to result in the daemon doing a re-init and then closing down.  I'm assuming it's due to whatever SAB does behind the scenes to restart itself compared to how it's starting via plugin.  Would very much like to be able to have it handle a restart within itself too.  That'd be perfect!

**Comment by Influencer** [comment]
Probably the easiest way to find out is invoking sabnzbd from the console,
then restarting from the sab gui so we can see whats being printed, might
give some clues as to why that's happening.

What case does it do this? When going from http to https only?

**Comment by overbyrn** [comment]
I'll do some troubleshooting.  Certainly seemed to be unhappy when I was swapping between http and https, but as you can imagine, I've been darting back and forth into the sab gui to tick/untick https and assign/blank https ports, so have to be honest and say I can't be sure if it barfs on all or just certain changes.  I did check the logs but it didn't really give much of a clue. I'll run sab from the command line and report back.

**Comment by overbyrn** [comment]
Ah-Ha!  Result.  Ran non-daemon in cmdline, clue came from ...
Traceback (most recent call last):
  File "/mnt/disk1/Services/sabnzbd/SABnzbd.py", line 1840, in <module>
    main()
  File "/mnt/disk1/Services/sabnzbd/SABnzbd.py", line 1634, in main
    os.chdir(org_dir)
OSError: [Errno 13] Permission denied: '/root'

Reason: I ran the process from the default PWD I happened to be in (/root).  Changed to world writeable dir, in this case /mnt/disk1 and re-ran.  This time a restart from SAB worked like a charm.  So it might be as simple as ensuring the rc.sabnzbd chdirs to something safe prior to running $CMDLINE.  Will continue to play...

**Comment by overbyrn** [comment]
Yup.  It was that simple.  Added cd /tmp ahead of executing CMDLINE and now I'm able to restart inside SABnzbd gui.  Have successfully tried restart with no changes, restart after enabling https (with a port), disabling https, enabling https (without a port).  Each time did a refresh on Unraid SAB gui page whereby it correctly recoginised process running status and more importantly correctly displays what ports it's running on as well as when just running on https over regular port, changing the hyperlink to https:// instead.  This last part is per our earlier discussion on the logic of what should happen. If you remember, the plan was to assume if we're inside the unraid gui, then we're on the local lan and if sab is up on a http port (with or without https), then to hyperlink to http:// and if sab is up on only https (which can only ever be on the value defined in the regular port), then serve up the hyperlink as https:// instead.

**Comment by Influencer** [comment]
Glad it was simple. Yeah, Saba logs aren't the best for debugging, I find
running without daemon is easier.

Won't have time tonight but ill look at the changes more in depth tomorrow.
From first look everything looks good. Will run it through the gauntlet
myself then assuming all is well push it through.

**Pull request closed without merging**
